# Generated by Django 4.1.1 on 2024-04-14 22:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('geometry', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.shape')),
            ],
        ),
    ]
