# Generated by Django 4.1.1 on 2024-04-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_place_segment_sequence_alter_segment_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='shape_id',
            new_name='shape',
        ),
    ]
