# Generated by Django 4.1.1 on 2024-04-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_shape_grid_max_lat_shape_grid_max_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='grid_max_lat',
            field=models.FloatField(default=-90.0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='grid_max_lon',
            field=models.FloatField(default=-180.0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='grid_min_lat',
            field=models.FloatField(default=90.0),
        ),
        migrations.AlterField(
            model_name='shape',
            name='grid_min_lon',
            field=models.FloatField(default=180.0),
        ),
    ]
