# Generated by Django 4.1.1 on 2024-05-22 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_gtfsshape'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 19, 30, 57, 876700, tzinfo=datetime.timezone.utc)),
        ),
    ]
