# Generated by Django 4.1.1 on 2024-06-11 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='day_type',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.CreateModel(
            name='HistoricSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('day_type', models.CharField(default='L', max_length=1)),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment')),
            ],
        ),
    ]
