# Generated by Django 4.1.1 on 2024-06-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_speed_day_type_historicspeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicspeed',
            old_name='shape_id',
            new_name='segment',
        ),
    ]
