# Generated by Django 4.1.1 on 2024-06-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_speed_temporal_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicspeed',
            name='temporal_segment',
            field=models.IntegerField(default=0),
        ),
    ]
