# Generated by Django 4.1.1 on 2024-07-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_alter_alert_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='voted_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='voted_positive',
            field=models.IntegerField(default=0),
        ),
    ]
