# Generated by Django 4.1.1 on 2024-08-20 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_alertthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='segment_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
