# Generated by Django 4.1.1 on 2024-08-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_segment_segment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed',
            name='speed',
        ),
        migrations.AddField(
            model_name='speed',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='speed',
            name='time_secs',
            field=models.FloatField(default=0),
        ),
    ]
