# Generated by Django 4.1.1 on 2024-08-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_remove_speed_speed_speed_distance_speed_time_secs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='voted_positive',
            new_name='useful',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='voted_negative',
            new_name='useless',
        ),
    ]
