# Generated by Django 4.1.1 on 2024-09-05 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0024_rename_voted_positive_alert_useful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
