# Generated by Django 4.1.1 on 2025-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_gtfsrttimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shape',
            name='lanes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
