# Generated by Django 4.1.1 on 2025-10-03 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_shape_bus_shape_lanes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('streets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('city', models.CharField(default='Provincia de Santiago', max_length=128)),
            ],
        ),
    ]
