# Generated by Django 4.1.1 on 2025-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0028_axles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axles',
            name='city',
            field=models.CharField(blank=True, default='Provincia de Santiago', max_length=128),
        ),
    ]
