# Generated by Django 4.1.1 on 2025-11-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_alter_axles_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_id', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment')),
            ],
        ),
    ]
