# Generated by Django 4.1.1 on 2025-11-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0030_trafficsignal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='lanes',
        ),
    ]
