# Generated by Django 4.1.1 on 2025-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_remove_shape_bus_remove_shape_lanes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsshape',
            name='route_id',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='bearing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
