# Generated by Django 4.1.1 on 2025-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0032_gtfsshape_route_id_segment_bearing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtfsshape',
            name='id',
        ),
        migrations.AlterField(
            model_name='gtfsshape',
            name='route_id',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='gtfsshape',
            name='shape_id',
            field=models.CharField(max_length=124, primary_key=True, serialize=False),
        ),
    ]
