# Generated by Django 4.1.1 on 2025-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0033_remove_gtfsshape_id_alter_gtfsshape_route_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='direction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
