# Generated by Django 4.1.1 on 2025-11-12 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0034_segment_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='id',
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
