# Generated by Django 4.1.1 on 2025-11-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0036_fix_segment_fk_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
        migrations.AlterField(
            model_name='historicspeed',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
        migrations.AlterField(
            model_name='services',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.segment'),
        ),
    ]
