# Generated by Django 4.1.1 on 2025-12-19 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0039_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=124), blank=True, null=True, size=None),
        ),
    ]
