# Generated by Django 4.1.1 on 2026-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0040_speed_services'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['segment', 'temporal_segment'], name='rest_api_al_segment_31dc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='rest_api_al_timesta_8c3a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='historicspeed',
            index=models.Index(fields=['segment', 'day_type', 'temporal_segment', '-timestamp'], name='rest_api_hi_segment_58acb6_idx'),
        ),
        migrations.AddIndex(
            model_name='speed',
            index=models.Index(fields=['segment', 'timestamp', 'temporal_segment'], name='rest_api_sp_segment_68a533_idx'),
        ),
        migrations.AddIndex(
            model_name='speed',
            index=models.Index(fields=['segment', 'temporal_segment'], name='rest_api_sp_segment_e88809_idx'),
        ),
    ]
