# Generated by Django 4.1.1 on 2024-05-22 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0002_alter_gpspulse_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspulse',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
