# Generated by Django 4.1.1 on 2024-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0003_alter_gpspulse_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpspulse',
            name='license_plate',
            field=models.CharField(default='NN', max_length=24),
        ),
    ]
