# Generated by Django 4.1.1 on 2025-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0006_alter_gpspulse_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpspulse',
            name='bearing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
