# Generated by Django 4.1.1 on 2025-11-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0007_gpspulse_bearing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpspulse',
            old_name='direction_id',
            new_name='direction',
        ),
    ]
