# Generated by Django 4.1.1 on 2025-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0008_rename_direction_id_gpspulse_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspulse',
            name='direction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
