# Generated by Django 4.1.1 on 2025-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0009_alter_gpspulse_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspulse',
            name='route_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
