# Generated by Django 4.1.1 on 2025-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs_rt', '0010_alter_gpspulse_route_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gpspulse',
            index=models.Index(fields=['timestamp'], name='gtfs_rt_gps_timesta_52d348_idx'),
        ),
    ]
