version: '3.7'

x-dev-server:
  &dev-server
  build:
    context: ..
    dockerfile: docker/Dockerfile
    target: dev
  env_file:
    - ./dev/backend_env
  volumes:
    - ../backend:/app/backend

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/NginxDockerfile
      args:
        - GIT_PERSONAL_TOKEN=${GITHUB_TOKEN}
        - VUE_APP_BASE_URL=${VUE_APP_BASE_URL}
    profiles: [ 'dev' ]
    ports:
      - "8080:80"
  web:
    profiles: [ 'dev', 'test' ]
    <<: *dev-server
    command: webserver-dev
    ports:
      - "8081:8000"
  db:
    profiles: [ 'dev', 'test' ]
    ports:
      - "5432:5432"