# Generated by Django 4.1.1 on 2024-03-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('trip_id', models.CharField(max_length=24)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
