name: UOCT - tests
on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - 'README.md'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4.1.1

      - name: Build and run tests
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request'))
        run: make test
